# Generated by Django 3.1.5 on 2021-02-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_basketball', '0002_auto_20210202_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='stadium',
        ),
        migrations.AddField(
            model_name='stadium',
            name='statistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_basketball.statistics', verbose_name='Statystyki'),
        ),
    ]
