# Generated by Django 3.1.5 on 2021-02-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_basketball', '0003_auto_20210203_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('add_wins', 'Can add wins for Team'),)},
        ),
    ]
