# Generated by Django 3.1.5 on 2021-02-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_basketball', '0004_auto_20210203_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadium',
            options={'permissions': (('add_match', 'Can add matches to the history'),)},
        ),
    ]
